# xz

#klib-y := xz_dec_syms.o xz_dec_stream.o xz_dec_lzma2.o
#klib-y += xz_dec_bcj.o
klib-y := xz_crc32.o xz_crc64.o xz_dec_stream.o xz_dec_lzma2.o xz_dec_bcj.o

# xz specific flag
EXTRA_KLIBCCFLAGS := -DXZ_DEC_ARM -DXZ_DEC_ARMTHUMB -DXZ_DEC_ANY_CHECK -DXZ_USE_CRC64
