.TH "wl_global" 3 "Fri Feb 13 2015" "Version 1.7.0" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_global \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBwl_display\fP * \fBdisplay\fP"
.br
.ti -1c
.RI "const struct \fBwl_interface\fP * \fBinterface\fP"
.br
.ti -1c
.RI "uint32_t \fBname\fP"
.br
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "wl_global_bind_func_t \fBbind\fP"
.br
.ti -1c
.RI "struct \fBwl_list\fP \fBlink\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
