.TH "wl_interface" 3 "Fri Feb 13 2015" "Version 1.7.0" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_interface \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "int \fBmethod_count\fP"
.br
.ti -1c
.RI "const struct \fBwl_message\fP * \fBmethods\fP"
.br
.ti -1c
.RI "int \fBevent_count\fP"
.br
.ti -1c
.RI "const struct \fBwl_message\fP * \fBevents\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
