.TH "wl_resource" 3 "Fri Feb 13 2015" "Version 1.7.0" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_resource \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBwl_object\fP \fBobject\fP"
.br
.ti -1c
.RI "wl_resource_destroy_func_t \fBdestroy\fP"
.br
.ti -1c
.RI "struct \fBwl_list\fP \fBlink\fP"
.br
.ti -1c
.RI "struct \fBwl_signal\fP \fBdestroy_signal\fP"
.br
.ti -1c
.RI "struct \fBwl_client\fP * \fBclient\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "\fBwl_dispatcher_func_t\fP \fBdispatcher\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
