.TH "wl_shm_pool" 3 "Fri Feb 13 2015" "Version 1.7.0" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_shm_pool \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBwl_resource\fP * \fBresource\fP"
.br
.ti -1c
.RI "int \fBrefcount\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "int32_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
