.TH "wl_shm_sigbus_data" 3 "Fri Feb 13 2015" "Version 1.7.0" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_shm_sigbus_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBwl_shm_pool\fP * \fBcurrent_pool\fP"
.br
.ti -1c
.RI "int \fBaccess_count\fP"
.br
.ti -1c
.RI "int \fBfallback_mapping_used\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
